# Generated by Django 2.0.2 on 2018-03-30 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(default='Base Case', max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
                ('current', models.NullBooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIntern.Case')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('doc_date', models.CharField(max_length=255)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='document_folder')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Base'), (2, 'Manager')], default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIntern.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIntern.Document'),
        ),
        migrations.AddField(
            model_name='case',
            name='documents',
            field=models.ManyToManyField(to='autoIntern.Document'),
        ),
        migrations.AddField(
            model_name='case',
            name='user_permissions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
