# Generated by Django 2.0.2 on 2018-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoIntern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='case',
        ),
    ]
