# Generated by Django 2.0.2 on 2018-04-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoIntern', '0002_remove_data_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
