# Generated by Django 2.0.2 on 2018-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoIntern', '0003_auto_20180407_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rangySelection',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
