# Generated by Django 2.0.2 on 2018-03-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoIntern', '0005_auto_20180326_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('manager', 'has manager permissions'), ('base', 'has base permissions')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='case',
            name='case_name',
            field=models.CharField(default='Base Case', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIntern.Case'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
